# Generated by Django 5.2.5 on 2025-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concerts', 'Concerts'), ('festivals', 'Festivals'), ('dj_parties', 'DJ Parties'), ('standup_comedy', 'Stand-up Comedy'), ('movie_premieres', 'Movie Premieres'), ('theatre', 'Theatre Performances'), ('opera_ballet', 'Opera & Ballet'), ('matches', 'Matches & Tournaments'), ('runs_cycling', 'Runs & Cycling'), ('yoga_wellness', 'Yoga & Wellness'), ('educational_courses', 'Educational Courses'), ('seminars', 'Seminars & Lectures'), ('masterclasses', 'Masterclasses'), ('business_workshops', 'Business Workshops'), ('exhibitions_art', 'Exhibitions & Art'), ('food_gastronomy', 'Food & Gastronomy'), ('online_events', 'Online Events')], default='concerts', max_length=50),
        ),
    ]
