# Generated by Django 5.2.5 on 2025-08-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventia_app', '0002_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
