# Generated by Django 5.2.5 on 2025-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventia_app', '0003_rename_data_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concerts', 'Concerts'), ('festivals', 'Festivals'), ('dj-parties', 'DJ Parties'), ('standup-comedy', 'Stand-up Comedy'), ('movie-premieres', 'Movie Premieres'), ('theatre', 'Theatre Performances'), ('opera-ballet', 'Opera & Ballet'), ('matches', 'Matches & Tournaments'), ('runs-cycling', 'Runs & Cycling'), ('yoga-wellness', 'Yoga & Wellness'), ('educational-courses', 'Educational Courses'), ('seminars', 'Seminars & Lectures'), ('masterclasses', 'Masterclasses'), ('business-workshops', 'Business Workshops'), ('exhibitions-art', 'Exhibitions & Art'), ('food-gastronomy', 'Food & Gastronomy'), ('online-events', 'Online Events')], default='concerts', max_length=50),
        ),
    ]
